# Generated by Django 4.0.4 on 2022-04-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.TextField(blank=True, max_length=255, null=True)),
                ('stop', models.BooleanField(default=False)),
            ],
        ),
    ]
